# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop
- master
- feature/*
- hotfix/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(date:yyyyMMdd)$(rev:.r)

steps:    
- task: NuGetAuthenticate@0
  displayName: Litium Nuget Authenticate
  inputs:
    nuGetServiceConnections: 'Litium Nuget Feed'
    forceReinstallCredentialProvider: true
- task: NuGetToolInstaller@1
  displayName: Install Nuget
- task: NodeTool@0
  displayName: Use Node Version 14.x
  inputs:
    versionSpec: '14.x'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
- task: Yarn@3
  inputs:
    projectDirectory: 'Src\Litium.Accelerator.Mvc\'
    arguments: 'install'
- task: Yarn@3
  inputs:
    projectDirectory: 'Src\Litium.Accelerator.Mvc\'
    arguments: 'run prod'
- task: NuGetCommand@2
  displayName: Restore Nugets
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
    externalFeedCredentials: 'Litium Nuget Feed'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



