# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop
- master
- feature/*
- hotfix/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(date:yyyyMMdd)$(rev:.r)

steps:

- task: NuGetAuthenticate@0
  displayName: 'Litium Nuget Authenticate'
  inputs:
    nuGetServiceConnections: 'Litium Nuget Feed'
    forceReinstallCredentialProvider: true
    
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget'

- task: NuGetCommand@2
  displayName: Restore Nugets
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
    externalFeedCredentials: 'Litium Nuget Feed'

- task: NodeTool@0
  displayName: 'Use Node Version 14.x'
  inputs:
    versionSpec: '14.x'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Yarn@3
  displayName: 'Yarn Install'
  inputs:
    projectDirectory: 'Src\Litium.Accelerator.Mvc\'
    arguments: 'install'

- task: Yarn@3
  displayName: 'Yarn run prod'
  inputs:
    projectDirectory: 'Src\Litium.Accelerator.Mvc\'
    arguments: 'run prod'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=Release /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SkipInvalidConfigurations=true /p:DeleteExistingFiles=True /p:publishUrl="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  condition: and( 	succeeded(),  	 	or(  		 		startsWith(variables['Build.SourceBranch'], 'refs/heads/develop'),  		 		startsWith(variables['Build.SourceBranch'], 'refs/heads/master'),  		 		startsWith(variables['Build.SourceBranchName'], 'develop'),  		 		startsWith(variables['Build.SourceBranchName'], 'master'),  		 		startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'),  		 		startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), 		startsWith(variables['Build.SourceBranchName'], 'upgrade') 	) 		 )
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: LitiumBuildArtifact